version: '3.2'

services:
  db:
    image: mariadb:10.2
    volumes:
      - ${BASE_VOL_PATH}db-data:/var/lib/mysql
    networks:
      - matomo-network      
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=matomo"
      - "MYSQL_USER=${SWARMLET_USERNAME:-matomo}"
      - "MYSQL_PASSWORD=${SWARMLET_PASSWORD:-matomo}"
    restart: always

  redis:
    image: redis:4.0-alpine
    restart: always
    networks:
      - matomo-network

  geoip-updater:
    image: crazymax/geoip-updater:latest
    volumes:
      - ${BASE_VOL_PATH}geoip-data:/data
    networks:
      - matomo-network
    env_file:
      - "./geoip-updater.env"
    restart: always

  matomo:
    image: crazymax/matomo:latest
    depends_on:
      - db
      - redis
    env_file:
      - "./matomo.env"
    restart: always
    volumes:
      - ${BASE_VOL_PATH}matomo-data:/data
      - ${BASE_VOL_PATH}geoip-data:/data/geoip
    networks:
      - matomo-network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.matomo.enable=true
        - traefik.matomo.port=8000
        - traefik.matomo.frontend.rule=Host:matomo.${DOMAIN}
        - traefik.matomo.frontend.entryPoints=http,https
        - traefik.matomo.frontend.passHostHeader=true
        - traefik.matomo.frontend.headers.SSLRedirect=true
        - traefik.matomo.frontend.headers.SSLHost=matomo.${DOMAIN}
        - traefik.matomo.frontend.headers.STSIncludeSubdomains=true
        - traefik.matomo.frontend.headers.STSPreload=true
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 120s

  cron:
    image: crazymax/matomo:latest
    depends_on:
      - matomo
    volumes:
      - ${BASE_VOL_PATH}matomo-data:/data
      - ${BASE_VOL_PATH}geoip-data:/data/geoip
    networks:
      - matomo-network
    env_file:
      - "./matomo.env"
    environment:
      - "SIDECAR_CRON=1"
      - "CRON_ARCHIVE=0 * * * *"
      - "ARCHIVE_OPTIONS=--concurrent-requests-per-website=3"
    healthcheck:
      disable: true
    restart: always

networks:
  matomo-network:
  traefik-public:
    external: true
