version: '3.7'

services:
  agent:
    build: .
    image: ${SWARMLET_REGISTRY}/deployer
    entrypoint: /entrypoint
    command: tail -f /dev/null
    networks:
      - swarmlet-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/swarmlet:/opt/swarmlet
      - ${VOL_PATH}/git-data:/home/git
    secrets:
      - swarmlet-user-secrets
    configs:
      - swarmlet-core-config
      - swarmlet-user-config
      - swarmlet-config
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 120s

networks:
  swarmlet-network:
    external: true

secrets:
  swarmlet-user-secrets:
    external: true

configs:
  swarmlet-core-config:
    external: true
  swarmlet-user-config:
    external: true
  swarmlet-config:
    external: true
