version: '3.3'

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    networks:
      - swarmpit-net
      - swarmlet-network
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.frontend.rule=Host:swarmpit.${DOMAIN}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

  db:
    image: couchdb:2.3.0
    volumes:
      - ${BASE_VOL_PATH}db-data:/opt/couchdb/data
    networks:
      - swarmpit-net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
      placement:
        constraints:
          - node.labels.swarmpit.db-data == true

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.40
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - swarmpit-net
      - swarmlet-network
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

networks:
  swarmpit-net:
    driver: overlay
    attachable: true
  swarmlet-network:
    external: true
  traefik-public:
    external: true

